# Generated by Django 3.2.4 on 2021-08-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('price', models.CharField(max_length=127, verbose_name='Price')),
                ('sale', models.CharField(blank=True, max_length=127, null=True, verbose_name='Sale Price')),
                ('image', models.ImageField(upload_to='course_images', verbose_name='Image 369x251 ')),
                ('summery', models.CharField(max_length=127, verbose_name='Summery')),
                ('requrements', models.CharField(blank=True, max_length=127, null=True, verbose_name='Requrements')),
                ('durations', models.IntegerField(blank=True, null=True, verbose_name='Quizzes')),
                ('leactures', models.IntegerField(blank=True, null=True, verbose_name='Leactures')),
                ('quizzes', models.IntegerField(blank=True, null=True, verbose_name='Quizzes')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Curse Category',
                'verbose_name_plural': 'Curse Categories',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Course_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Course comment',
                'verbose_name_plural': 'Courses comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short Description')),
                ('lecture', models.FloatField(blank=True, verbose_name='Lecture')),
                ('time', models.FloatField(blank=True, verbose_name='Lecture time')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curriculums',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('auditor', models.CharField(max_length=127, verbose_name='Auditor')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Event images', verbose_name='Image')),
                ('singleimage', models.ImageField(upload_to='Event images', verbose_name='Single Image')),
                ('address', models.CharField(max_length=127, verbose_name='Address')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Teacher_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Teacher Comment',
                'verbose_name_plural': 'Teacher Commnets',
                'ordering': ('fullname', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=127, null=True, verbose_name='Job')),
                ('short_description', models.CharField(max_length=127, null=True, verbose_name='Short description')),
                ('about', models.CharField(max_length=127, null=True, verbose_name='About')),
                ('acchivments', models.CharField(max_length=127, null=True, verbose_name='Achivments')),
                ('objective', models.CharField(max_length=127, null=True, verbose_name='My Objective')),
                ('image', models.ImageField(upload_to='teacherinfo_image', verbose_name='Info Image 270x308')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Teacher Info',
                'verbose_name_plural': 'Teachers Infos',
                'ordering': ('user', '-created_at'),
            },
        ),
    ]
