# Generated by Django 3.2.4 on 2021-08-01 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
