# Generated by Django 3.2.4 on 2021-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Bashliq')),
                ('short_description', models.TextField(blank=True, verbose_name='Qisa mezmun')),
                ('description', models.TextField(null=True, verbose_name='Mezmun')),
                ('image', models.ImageField(upload_to='blog_image', verbose_name='Shekil')),
                ('category', models.IntegerField(choices=[(1, 'Travel'), (2, 'Food')], verbose_name='Kategory')),
                ('created_ad', models.DateField(auto_now_add=True)),
                ('updated_ad', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
    ]
