# Generated by Django 3.2.4 on 2021-07-13 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short description')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='blog_images', verbose_name='Image')),
                ('slug', models.SlugField(max_length=160, unique_for_date='created_at', verbose_name='Slug')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogauthor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=127, verbose_name='Subject')),
                ('phone', models.CharField(max_length=127, verbose_name='Phone')),
                ('message', models.TextField(help_text='You can send your mesaage from here', verbose_name='Message')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='FullName')),
                ('price', models.CharField(max_length=127, verbose_name='Price')),
                ('image', models.ImageField(upload_to='course_images', verbose_name='Image')),
                ('durations', models.CharField(max_length=127, verbose_name='Duration')),
                ('leactures', models.CharField(max_length=127, verbose_name='Leactures')),
                ('quizzes', models.CharField(max_length=127, verbose_name='Quizzes')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Curse Category',
                'verbose_name_plural': 'Curse Categories',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('price', models.CharField(max_length=127, verbose_name='Price')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('seller', models.CharField(max_length=127, verbose_name='Seller')),
                ('image', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image1', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image2', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image3', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image4', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image5', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image6', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image7', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('image8', models.ImageField(upload_to='order_images', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Order Category',
                'verbose_name_plural': 'Order Categories',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('job', models.CharField(max_length=127, verbose_name='Job')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short description')),
                ('about', models.CharField(max_length=127, verbose_name='About')),
                ('acchivments', models.CharField(max_length=127, verbose_name='Achivments')),
                ('objective', models.CharField(max_length=127, verbose_name='My Objective')),
                ('image', models.ImageField(upload_to='teacher_images', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='firstapp.course')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ('full_name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Teacher_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='firstapp.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher Comment',
                'verbose_name_plural': 'Teacher Commnets',
                'ordering': ('full_name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Order_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='firstapp.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order comment',
                'verbose_name_plural': 'Order comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title')),
                ('start', models.DateTimeField(verbose_name='Start time')),
                ('end', models.DateTimeField(verbose_name='End time')),
                ('auditor', models.CharField(max_length=127, verbose_name='Auditor')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='Event images', verbose_name='Image')),
                ('singleimage', models.ImageField(upload_to='Event images', verbose_name='Single Image')),
                ('address', models.CharField(max_length=127, verbose_name='Address')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='firstapp.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('title', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Course_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='firstapp.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course comment',
                'verbose_name_plural': 'Courses comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='firstapp.course_category'),
        ),
        migrations.CreateModel(
            name='Blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_blog', to='firstapp.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Blog Comment',
                'verbose_name_plural': 'Blog Comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='firstapp.blog_category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='firstapp.Tag', verbose_name='Tag'),
        ),
    ]
