# Generated by Django 3.2.4 on 2021-06-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.IntegerField(choices=[(1, 'Travel'), (2, 'Food')], verbose_name='Kategory'),
        ),
    ]
