# Generated by Django 3.2.4 on 2021-07-10 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210710_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=127, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
