# Generated by Django 3.2.4 on 2021-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210629_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='FullName')),
                ('short_description', models.CharField(max_length=127, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('message', models.TextField(help_text='You can send your mesaage from here', verbose_name='Message')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is published')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('title', '-created_at'),
            },
        ),
    ]
