# Generated by Django 3.2.4 on 2021-07-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_blog_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='parent',
        ),
        migrations.CreateModel(
            name='Blog_comment_reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127, verbose_name='FullName')),
                ('email', models.EmailField(max_length=127, verbose_name='E-mail')),
                ('content', models.TextField(verbose_name='Content')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='firstapp.blog_comment')),
            ],
            options={
                'verbose_name': 'Blog Comment reply',
                'verbose_name_plural': 'Blog Comments reply',
                'ordering': ('-created_at',),
            },
        ),
    ]
