# Generated by Django 3.2.4 on 2021-07-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_category',
        ),
        migrations.RemoveField(
            model_name='order_comment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Comment',
        ),
    ]
