# Generated by Django 3.2.4 on 2021-07-10 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210710_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='singleimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Event images', verbose_name='Single Image'),
            preserve_default=False,
        ),
    ]
