# Generated by Django 3.2.4 on 2021-07-01 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='shop_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=127, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(default=django.utils.timezone.now, max_length=127, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
