# Generated by Django 3.2.4 on 2021-07-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.BooleanField(choices=[(False, 'Teacher'), (True, 'Student')], verbose_name='Category'),
        ),
    ]
